spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:/Apigee/micro-services/Work/backup-plan/supplier-collaboration-config-dev
      #refresh: true
#      delay: 5000
#username: sunilsoni@live.in
#password: sunil@git0102
#file://C:/Apigee/micro-services/Work/supplier-collaboration-config-dev
#D:/home/site/wwwroot/supplier-collaboration-config
#https://github.com/sunilsoni/supplier-collaboration-config
#file://C:/Apigee/micro-services/Work/supplier-collaboration-config
#https://github.com/sunilsoni/sample-config
# While in development mode, you can configure the config server to pick up configuration files from
# the file system

#uri: file://C:/Apigee/micro-services/Work/sample-config

# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 8888